# Generated by Django 3.1.2 on 2021-06-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Singer',
        ),
        migrations.AlterField(
            model_name='channel',
            name='bgimgofalbum',
            field=models.ImageField(default='bg.jpg', upload_to='bg_img/'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='imgofablum',
            field=models.ImageField(default='user.png', upload_to='imgofablum'),
        ),
    ]
