# Generated by Django 3.1.2 on 2021-07-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclist', '0003_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='artist',
            name='bg_imgs',
            field=models.ImageField(default='bg.jpg', upload_to='bg_img/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='lastname',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
