# Generated by Django 3.1.2 on 2021-07-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclist', '0006_auto_20210703_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='favourite',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
