# Generated by Django 3.1.2 on 2021-07-08 18:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musiclist', '0008_auto_20210709_0019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lsitenlater',
            new_name='Listenlater',
        ),
    ]
