# Generated by Django 3.1.2 on 2021-07-09 10:49

from django.db import migrations, models
import musiclist.validators


class Migration(migrations.Migration):

    dependencies = [
        ('musiclist', '0009_auto_20210709_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='credit',
        ),
        migrations.AddField(
            model_name='song',
            name='album_name',
            field=models.CharField(default=1, max_length=90000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='time_length',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='update',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='update',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='update',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='listenlater',
            name='update',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.CharField(default='', max_length=90000),
        ),
        migrations.AlterField(
            model_name='song',
            name='movie',
            field=models.CharField(default='', max_length=90000),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=90000),
        ),
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.CharField(max_length=90000),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to='musics/', validators=[musiclist.validators.validate_is_audio]),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.CharField(max_length=90000),
        ),
        migrations.AlterField(
            model_name='song',
            name='update',
            field=models.DateTimeField(blank=True),
        ),
    ]
